### ISSUE TITLE
stalk installation issues on raspberry pi - jessie

### ISSUE THREAD

**Issue by ipmstyle** [321core/STALK-INSTALL#8]
solve :
- **re-install pip**
  - apt-get remove python-pip
  - wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py install
- **install stalk**
  - sh install-raspberrypi.py

**Comment by jeonghoonkang** [comment]
라즈베리파이 Zero / Jessie 에서 아래와 같은 에러 발생

pi@raspi-zero-0 ~ $ sudo python get-pip.py install
Collecting install
  Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install

**Comment by jeonghoonkang** [comment]
FYI, pip installation

2016/01/22

wget https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip
unzip distribute-0.7.3.zip
sudo python setup.py install
sudo easy_install pip

It was installation success in the RaspberryPi Zero / Jessie lite version
